# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Utils/02_asian_handicap_pnl.ipynb.

# %% auto 0
__all__ = ['ah_pnl']

# %% ../../nbs/Utils/02_asian_handicap_pnl.ipynb 4
def ah_pnl(
    obs_gd: int,  # Game goal-difference.
    ah_line: float,  # Asian line could be integer, half or quarter line.
    ah_odds: float,  # Asian handicap odds for the given side.
) -> float:  # unit bet pnl
    "provide the asian outcome given for aunit bet."
    # team advantage
    gd_advantage = obs_gd + ah_line

    # deal with all advantage cases
    # 0 advantage
    if gd_advantage == 0:
        return 0.0
    # positive adv and higher than 0.5
    # win the bet
    elif gd_advantage >= 0.5:
        return ah_odds - 1
    # negative adv and < than -0.5
    # lose the bet
    elif gd_advantage <= -0.5:
        return -1.0

    # positive adv and equal to 0.25
    # win the half
    elif gd_advantage == 0.25:
        return (ah_odds - 1) * 0.5

    # positive adv and equal to -0.25
    # lose the half stake of your bets.
    elif gd_advantage == -0.25:
        return -0.5
    else:
        return 0.0
