# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Config/000_config.ipynb.

# %% auto 0
__all__ = ['pkg_config', 'local_config', 'CONFIG', 'DB_HOSTS']

# %% ../../nbs/Config/000_config.ipynb 4
import toml
import logging
from pathlib import Path

# Read local `config.toml` file.
pkg_config = Path("../../config.toml")
local_config = Path("/secrets/config.toml")
CONFIG = toml.load(pkg_config if pkg_config.exists() else local_config)

## defined database hosts
DB_HOSTS = set([db for db in CONFIG["databases"]])

## config
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
