# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Config/000_config.ipynb.

# %% auto 0
__all__ = ['pkg_config', 'pkg_config_2', 'pkg_config_3', 'CONFIG', 'DB_HOSTS']

# %% ../../nbs/Config/000_config.ipynb 4
import toml
import logging
from pathlib import Path

# Read local `config.toml` file.
pkg_config = Path("../../config.toml")
pkg_config_2 = Path("../config.toml")
pkg_config_3 = Path("./config.toml")

if pkg_config.exists():
    pkg_config = pkg_config
elif pkg_config_2.exists():
    pkg_config = pkg_config_2
else:
    pkg_config = pkg_config_3


CONFIG = toml.load(pkg_config)

# Defined database hosts.
DB_HOSTS = set([db for db in CONFIG["databases"]])

# Config.
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
)
