# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Config/000_config.ipynb.

# %% auto 0
__all__ = ['logger', 'pkg_config', 'pkg_config_2', 'pkg_config_3', 'secret_config', 'CONFIG', 'DB_HOSTS']

# %% ../../nbs/Config/000_config.ipynb 4
import toml
import logging
import sys
from pathlib import Path

# Config.
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
)

logger = logging.getLogger(__name__)

# Read local `config.toml` file.
pkg_config = Path("../../config.toml")
pkg_config_2 = Path("../config.toml")
pkg_config_3 = Path("./config.toml")
secret_config = Path("/secrets/config.toml")

if pkg_config.exists():
    pkg_config = pkg_config
elif pkg_config_2.exists():
    pkg_config = pkg_config_2
elif pkg_config_3.exists():
    pkg_config = pkg_config_3
elif secret_config:
    pkg_config = secret_config
else:
    logger.error("No config file found !")
    sys.exit()

CONFIG = toml.load(pkg_config)

# Defined database hosts.
DB_HOSTS = set([db for db in CONFIG["databases"]])
