# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/betting_env',
                'doc_host': 'https://MeherKharbachi.github.io',
                'git_url': 'https://github.com/MeherKharbachi/betting_env',
                'lib_path': 'betting_env'},
  'syms': {'betting_env.core': {'betting_env.core.foo': ('core.html#foo', 'betting_env/core.py')}}}
